---
- name: "Install and configure namenode"
  hosts: namenodes
  become: true
  roles:
    - namenode

# - name: Print the gateway for each host when defined
#   debug: msg="Namenode is {{ namenode }}"

- name: "Install and configure datanode"
  hosts: datanodes
  become: true
  roles:
    - datanode
