---
- name: "Install and configure namenode"
  hosts: namenodes
  become: true
  roles:
    - namenode

- name: "Install and configure datanode"
  hosts: datanodes
  become: true
  roles:
    - datanode
